# Generated by Django 4.2.7 on 2023-11-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='videopost',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videopost',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videopost',
            name='video_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
