# Generated by Django 4.2.7 on 2023-11-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_videopost_description_videopost_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoPost',
        ),
    ]
