# Generated by Django 4.2.7 on 2023-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
